# base stage
FROM node:20-alpine as base

RUN mkdir -p /workdir

WORKDIR /workdir/app

# prod state
FROM base as dev

COPY package.json  .

RUN npm install

COPY prisma prisma

RUN npx prisma generate

COPY . . 

EXPOSE 9000

CMD ["npm", "run", "start:dev"]